name: ci

on:
  push:
    branches:
      - macos-ci

  pull_request:
    branches:
      - master

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu packages
      run: grep 'sudo apt install' INSTALL | sed 's/\$//' | sh
    - name: Compile
      run: make -C GUI/xephem
